=== robee05/proyectoxml/poke.dtd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!ELEMENT pokedex (pokemon)>
<!ELEMENT pokemon (url_imagen, datos_generales, tipologia, stats_base, evoluciones, atributo, tipo3)>
<!ATTLIST pokemon nombre CDATA #REQUIRED>
<!ATTLIST pokemon num_pokedex CDATA #REQUIRED>
<!ELEMENT url_imagen EMPTY>
<!ATTLIST url_imagen
        imagen CDATA #IMPLIED
        tipo_imagen NOTATION (jpg | gif | png) #IMPLIED>
<!ELEMENT datos_generales (altura, peso, sexo, categoria, habilidad)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT peso (#PCDATA)>
<!ELEMENT sexo (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT habilidad (#PCDATA)>
<!ELEMENT tipologia (tipos, debilidades, fortalezas)>ยบ
<!ELEMENT tipos (tipo1)>
<!ELEMENT tipo1 (descripcion)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT debilidades (debilidad)>
<!ELEMENT debilidad (tipo2, efectividad)>
<!ELEMENT tipo2 (#PCDATA)>
<!ELEMENT efectividad (#PCDATA)>
<!ELEMENT fortalezas (fortaleza)>
<!ELEMENT fortaleza (tipo3, efectividad)>
<!ELEMENT tipo3 (#PCDATA)>
<!ELEMENT stats_base (ps, at, def, spat, spde, vel)>
<!ELEMENT ps (#PCDATA)>
<!ELEMENT at (#PCDATA)>
<!ELEMENT def (#PCDATA)>
<!ELEMENT spat (#PCDATA)>
<!ELEMENT spde (#PCDATA)>
<!ELEMENT vel (#PCDATA)>
<!ELEMENT evoluciones (evolucion, bool)>
<!ELEMENT evolucion (orden, num_pokedex)>
<!ELEMENT orden (#PCDATA)>
<!ELEMENT num_pokedex (#PCDATA)>
<!ELEMENT bool (#PCDATA)>
<!ATTLIST bool nombre CDATA #REQUIRED>
<!ELEMENT atributo EMPTY>

=== robee05/proyectoxml/pokemon.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<?xml-stylesheet type="text/xsl" href="pok.xslt"?>

<!DOCTYPE pokedex SYSTEM "poke.dtd">
    <pokedex>
		<pokemon nombre="bulbasaur" num_pokedex="1">
            <url_imagen imagen="pokemon.jpg"
                        tipo_imagen="jpg"/>
            <datos_generales>
                <altura>0.45</altura>
                <peso>20</peso>
                <sexo>M/F</sexo>
                <categoria>Semilla</categoria>
                <habilidad>Espesura</habilidad>
            </datos_generales>
            <tipologia>
                <tipos>
                    <tipo1>
                        <descripcion>Planta</descripcion>
                    </tipo1>
                </tipos>
                <debilidades>
                    <debilidad>
                        <tipo2>Fuego</tipo2>
                        <efectividad>x2</efectividad>
                        <tipo2>Volador</tipo2>
                        <efectividad>x2</efectividad>
                    </debilidad>
                </debilidades>
                <fortalezas>
                    <fortaleza>
                        <tipo3>Agua</tipo3>
                        <efectividad>x2</efectividad>
                        <tipo3>Tierra</tipo3>
                        <efectividad>x2</efectividad>
                    </fortaleza>
                </fortalezas>
            </tipologia>
            <stats_base>
                <ps>30</ps>
                <at>10</at>
                <def>12</def>
                <spat>15</spat>
                <spde>13</spde>
                <vel>5</vel>
            </stats_base>
            <evoluciones>
                <evolucion>
                    <orden>-1</orden>
                    <num_pokedex>2</num_pokedex>
                </evolucion>
                <bool nombre="tiene_evolucion">[true | false]</bool>
            </evoluciones>
        </pokemon>
	</pokedex>
